graph TD
    A[Frontend React / TypeScript] --> B[Routes]
    B --> C[Pages]
    C --> D[Components]
    C --> E[Services API]
    E --> F[Backend Spring Boot]
    F --> G[Controllers]
    G --> H[Services]
    H --> I[Repositories]
    I --> J[Base de données MySQL]
    H --> K[DTO / Mapper]
    F --> L[Security / Config / Exceptions]
